on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

name: Linux aarch64

jobs:
  check:
    name: Build
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.84.0

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: cargo build
        run: cargo build