on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

name: macOS x86_64

jobs:
  build:
    name: Build
    runs-on: macos-13
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.9
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.84.0

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: cargo build
        run: cargo build