on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

name: macOS aarch64

jobs:
  check:
    name: Check
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.84.0
        with:
          components: clippy

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: cargo clippy
        run: cargo clippy -- -D warnings

  test:
    name: Run tests
    runs-on: macos-14
    env:
      # The first aarch64 target
      MACOSX_DEPLOYMENT_TARGET: 11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.84.0

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: cargo build
        run: cargo build

      - name: cargo test
        run: cargo test -- --nocapture