[package]
name = "reaper-fluent"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
# Own dependencies
reaper-medium.workspace = true
reaper-low.workspace = true
fragile.workspace = true

[dev-dependencies]
trybuild.workspace = true